name: Django CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      working-directory: ./blogapp/blog
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Tests
      working-directory: ./blogapp/blog
      run: |
        python manage.py test
        
    - name: Collect static files
      working-directory: ./blogapp/blog
      run: |
        python manage.py collectstatic --noinput
        
    - name: Create deployment package
      working-directory: ./blogapp/blog
      run: |
        mkdir -p ../deployment
        cp -r $(ls -A | grep -v "deployment") ../deployment/
        pip freeze > ../deployment/requirements-freeze.txt
          
    - name: Archive deployment package
      working-directory: ./blogapp
      run: |
        tar -czvf django-blog-${{ github.sha }}.tar.gz deployment/
          
    - name: Upload deployment artifact
      uses: actions/upload-artifact@v4
      with:
        name: django-blog-deployment
        path: ./blogapp/django-blog-${{ github.sha }}.tar.gz