name: Build Docker Images for Blog and Flask App
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      # Step 3: Build Django Docker image
      - name: Build Blog (Django) Docker image
        run: |
          cd blogapp  # Navigate to Django app folder
          docker build -t blogapp/blog:${{ github.sha }} .
      
      # Step 4: Push Django Docker image
      - name: Push Blog (Django) Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag blog-app:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/blog-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/blog-app:${{ github.sha }}
          docker tag blog-app:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/blog-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/blog-app:latest
      
      # Step 5: Build Flask Docker image
      - name: Build Flask Docker image
        run: |
          cd flask_app  # Navigate to Flask app folder
          docker build -t flask-app:${{ github.sha }} .
      
      # Step 6: Push Flask Docker image
      - name: Push Flask Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag flask-app:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:${{ github.sha }}
          docker tag flask-app:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest